apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nisha-deploy
  name: nisha-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nisha-deploy
  template:
    metadata:
      labels:
        app: nisha-deploy
    spec:
      containers:
        - image: httpd:alpine3.13
          name: httpd
          command: ["/bin/bash", "-c"] # override the default command
          args: ["sleep 5; exit 1"] # sleep for 5 seconds then exit with an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
status: {}
