apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4=" # base64 for "admin"
  MONGO_INITDB_ROOT_PASSWORD: "cGFzc3dvcmQxMjM="  # base64 for "password123"