apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque
data:
  MONGODB_USER: 'YWRtaW4='  # base64 for "admin"
  MONGODB_PASSWORD: 'cGFzc3dvcmQxMjM='  # base64 for "password123"